let albums= [
	{
        "id": 1,
        "title": "사랑은 마치",
        "singer": "",
        "img": "./images/1. 사랑은 마치.jpg",
        "elbumTitle": "레드북"
	},
    {
        "id": 2,
        "title": "Defying Gravity",
        "singer": "",
        "img": "./images/2. Defying Gravity.jpg",
		"elbumTitle": "위키드"
	},
    {
        "id": 3,
        "title": "거인을 데려와",
        "singer": "",
        "img": "./images/3. 거인을 데려와.jpg",
        "elbumTitle": "시라노"
	},
    {
        "id": 4,
        "title": "paper Plane",
        "singer": "Peder Elias",
        "img": "./images/4. paper Plane.jpg",
		"debut" :"2018년 8월 24일", 
		"genre": "팝, R&B, 소울 음악, 일렉트로니카",
		"activity": "솔로"
	},
    {
        "id": 5,
        "title": "IDGAF",
        "singer": "Dua Lipa",
        "img": "./images/5. IDGAF.jpg",
		"elbumTitle": "Dua Lipa (Deluxe)",
        "elbumImage": "",
		"debut" :"2015년 Dua Lipa 1집", 
		"agency": "워너 뮤직 그룹 ",
		"activity": "솔로"
	},
    {
        "id": 6,
        "title": "Fly Me to the Moon",
        "singer": "불명",
        "img": "./images/6. Fly Me to the Moon.jpg",
		"elbumTitle": "It Might as Well Be Swing",
        "elbumImage": "",
		"genre": "보컬 재즈",
		"agency": "리프라이즈",
		"activity": ""
	},
    {
        "id": 7,
        "title": "L-O-V-E",
        "singer": "Nat King Cole",
        "img": "./images/7. L-O-V-E.jpg",
		"elbumTitle": "L-O-V-E",
        "elbumImage": "",
		"debut" :"1936", 
		"genre": "팝, 재즈",
		"activity": "솔로"
	},
    {
        "id": 8,
        "title": "Don’t Worry be Happy",
        "singer": "Bobby McFerrin",
        "img": "./images/8. Don’t Worry be Happy.jpg",
		"elbumTitle": "Simple Pleasures",
        "elbumImage": "",
		"debut" :"1970년대", 
		"genre": "레게, 재즈, 아카펠라",
		"agency": "EMI-Manhattan",
		"activity": "솔로"
	},
    {
        "id": 9,
        "title": "Piano Concerto in A Minor",
        "img": "./images/9. Piano Concerto in A Minor.jpg",
		"genre": "클래식"
	},
    {
        "id": 10,
        "title": "Le Tombeau de Couperin",
        "img": "./images/10. Le Tombeau de Couperin.jpg",
		"genre": "클래식",
	},
    {
        "id": 11,
        "title": "Pour le piano II. Sarabande",
        "img": "./images/11. Pour le piano II. Sarabande.jpg",
		"genre": "클래식",
	},
    {
        "id": 12,
        "title": "악몽",
        "singer": "애쉬 아일랜드",
        "img": "./images/12. 악몽.jpg",
		"elbumTitle": "MORE ASH",
        "elbumImage": "",
		"debut" :"2018년 11월 12일", 
		"genre": "힙합, R&B, 이모 랩, 트랩, 록, 팝",
		"agency": "AMBITION MUSIK ",
		"activity": "PABLO MU2IK"
	},
    {
        "id": 13,
        "title": "Good Night (Feat. BE'O)",
        "singer": "Coogie",
        "img": "./images/13. Good Night.jpg",
		"elbumTitle": "RE:UP",
        "elbumImage": "",
		"debut" :"2018년 3월", 
		"genre": "힙합",
		"agency": "AOMG",
		"activity": "HIVE, YELOWS MOB"
	},
    {
        "id": 14,
        "title": "산책",
        "singer": "OVAN",
        "img": "./images/14. 산책.jpg",
		"elbumTitle": "산책",
        "elbumImage": "",
		"debut" :"2017년 3월 2일", 
		"genre": "싱어송라이트",
		"agency": "로맨틱팩토리",
		"activity": "솔로"
	},
    {
        "id": 15,
        "title": "시차(We Are)(feat Loco, GRAY)",
        "singer": "우원재",
        "img": "./images/15. 시차.jpg",
		"elbumTitle": "We Are",
        "elbumImage": "",
		"debut" :"2017년 9월 4일", 
		"genre": "힙합",
		"agency": "AOMG",
		"activity": "Gates"
	},
    {
        "id": 16,
        "title": "한 페이지가 될 수 있게",
        "singer": "DAY6",
        "img": "./images/16. 한 페이지가 될 수 있게.jpg",
		"elbumTitle": "The Book of Us: Gravity",
        "elbumImage": "",
		"debut" :"2015년 9월 7일", 
		"genre": "팝 록, 모던 록, 파워 팝, 팝 펑크, 얼터너티브 록, 헤비메탈, 신스팝, 록 발라드",
		"agency": "JYP",
		"activity": "그룹"
	},
    {
        "id": 17,
        "title": "맞네",
        "singer": "루시",
        "img": "./images/17. 맞네.jpg",
		"elbumTitle": "BLUE",
        "elbumImage": "",
		"debut" :"2020년 5월 8일", 
		"genre": "앰비언스 팝",
		"agency": "미스틱스토리",
		"activity": "그룹"
	},
    {
        "id": 18,
        "title": "옥탑방",
        "singer": "엔플라잉",
        "img": "./images/18. 옥탑방.jpg",
		"elbumTitle": "",
        "elbumImage": "",
		"debut" :"2015년 5월 20일", 
		"genre": "K-POP, 얼터너티브 록, 팝, 발라드, 댄스, 힙합",
		"agency": "FNC",
		"activity": "그룹"
	},
    {
        "id": 19,
        "title": "나는 나비",
        "singer": "YB",
        "img": "./images/19. 나는 나비.jpg",
		"elbumTitle": "흰수염고래",
        "elbumImage": "",
		"debut" :"1994년 말", 
		"genre": "록",
		"agency": "디컴퍼니",
		"activity": "그룹"
	},
    {
        "id": 20,
        "title": "오리 날다",
        "singer": "체리필터",
        "img": "./images/20. 오리 날다.jpg",
		"elbumTitle": "The Third Eye",
        "elbumImage": "",
		"debut" :"2000년 정규 1집 Head-Up", 
		"genre": "록",
		"agency": "뮤직팜",
		"activity": "그룹"
	},
    {
        "id": 21,
        "title": "낭만고양이",
        "singer": "체리필터",
        "img": "./images/21. 낭만고양이.jpg",
		"elbumTitle": "Made In Korea?",
        "elbumImage": "",
		"debut" :"2000년 정규 1집 Head-Up", 
		"genre": "록",
		"agency": "뮤직팜",
		"activity": "그룹"
	},
    {
        "id": 22,
        "title": "그대 없이는 못살아",
        "singer": "패티 김",
        "img": "./images/22. 그대 없이는 못살아.jpg",
		"elbumTitle": "패티김 History",
        "elbumImage": "",
		"debut" :"1958년", 
		"genre": "팝보컬",
		"agency": "PK 프로덕션",
		"activity": "솔로"
	},
    {
        "id": 23,
        "title": "미인",
        "singer": "신중현과 엽전들",
        "img": "./images/23. 미인.jpg",
		"elbumTitle": "신중현과 엽전들 제1집",
        "elbumImage": "",
		"debut" :"1974년 8월 25일", 
		"genre": "사이키델릭 록, 하드 록, R&B",
		"agency": "지구레코드",
		"activity": "그룹"
	},
    {
        "id": 24,
        "title": "아니 벌써",
        "singer": "산울림",
        "img": "./images/24. 아니 벌써.jpg",
		"elbumTitle": "산울림 새 노래 모음 - 아니 벌써",
        "elbumImage": "",
		"debut" :"1977년 9월 12일", 
		"genre": "포크 록, 프로그레시브 록, 하드 록, 사이키델릭 록",
		"agency": "서라벌레코드 로엔 엔터테인먼트",
		"activity": "그룹"
	},
    {
        "id": 25,
        "title": "stay with me",
        "singer": "마츠바라 미키",
        "img": "./images/25. stay with me.jpg",
		"elbumTitle": "Pocket Park",
        "elbumImage": "",
		"debut" :"1979년 11월 5일", 
		"genre": "시티 팝",
		"agency": "포니캐년",
		"activity": "솔로"
	},
    {
        "id": 26,
        "title": "어쩌다 마주친 그대",
        "singer": "송골매",
        "img": "./images/26. 어쩌다 마주친 그대.jpg",
		"elbumTitle": "송골매 2집",
        "elbumImage": "",
		"debut" :"1979년", 
		"genre": "하드 록, 팝 록, 팝 메탈, 재즈 록, 사이키델릭 록, 로큰롤, 하우스 음악, 유로댄스 디스코, 기타 등등",
		"activity": "밴드"
	},
    {
        "id": 27,
        "title": "J에게",
        "singer": "이선희",
        "img": "./images/27. J에게.jpg",
		"elbumTitle": "아! 옛날이여",
        "elbumImage": "",
		"debut" :"1984년", 
		"genre": "POP",
		"agency": "후크엔터테인먼트 ",
		"activity": "솔로"
	},
    {
        "id": 28,
        "title": "빙글빙글",
        "singer": "나미",
        "img": "./images/28. 빙글빙글.jpg",
		"elbumTitle": "나미 골든엘범",
        "elbumImage": "",
		"debut" :"1967년", 
		"genre": "댄스 팝, 발라드",
		"activity": "1967년 영화 '엘레지의 여왕'"
	},
    {
        "id": 29,
        "title": "리듬속의 그춤을",
        "singer": "김완선",
        "img": "./images/29. 리듬속의 그춤을.jpg",
		"elbumTitle": "The Original",
        "elbumImage": "",
		"debut" :"1986년", 
		"genre": "POP",
		"agency": "KWCunflower",
		"activity": "솔로"
	},
    {
        "id": 30,
        "title": "비행기",
        "singer": "거북이",
        "img": "./images/30. 비행기.jpg",
		"elbumTitle": "거북이 사요!!",
        "elbumImage": "",
		"debut" :"2001년 12월 20일", 
		"genre": "랩, 힙합, 발라드, 댄스",
		"agency": "소나무엔터테인먼트",
		"activity": "그룹"
	},
    {
        "id": 31,
        "title": "고속도로 로망스",
        "singer": "윤종신",
        "img": "./images/31. 고속도로 로망스.jpg",
		"elbumTitle": "행보 2013 윤종신",
        "elbumImage": "",
		"debut" :"1990년 7월 15일", 
		"genre": "발라드, 팝, 어덜트 컨템포러리",
		"agency": "미스틱스토리",
		"activity": "솔로"
	},
    {
        "id": 32,
        "title": "휠릴리",
        "singer": "이수영",
        "img": "./images/32. 휠릴리.jpg",
		"elbumTitle": "The Colors Of My Life",
        "elbumImage": "",
		"debut" :"1999년", 
		"genre": "팝",
		"agency": "뉴에라프로젝트",
		"activity": "솔로"
	},
    {
        "id": 34,
        "title": "눈의 꽃",
        "singer": "나카시마 미카",
        "img": "./images/34. 눈의 꽃.jpg",
		"elbumTitle": "LOVE",
        "elbumImage": "",
		"debut" :"2001년", 
		"genre": "J팝",
		"agency": "소니 뮤직 엔터테인먼트",
		"activity": "솔로"
	},
    {
        "id": 35,
        "title": "다시 만난 세계",
        "singer": "소녀시대",
        "img": "./images/35. 다시 만난 세계.jpg",
		"elbumTitle": "소녀시대 Girl's Generation",
        "elbumImage": "",
		"debut" :"2007년 8월 5일", 
		"genre": "댄스, 발라드, 일렉트로닉 뮤직, R&B, 힙합",
		"agency": "SM",
		"activity": "그룹"
	},
    {
        "id": 36,
        "title": "왠지",
        "singer": "다이아",
        "img": "./images/36. 왠지.jpg",
		"elbumTitle": "Do It Amazing",
        "elbumImage": "",
		"debut" :"2015년 9월 14일", 
		"genre": "pop",
		"agency": "포켓돌스튜디오",
		"activity": "그룹"
	},
    {
        "id": 37,
        "title": "결혼까지 생각했어",
        "singer": "휘성",
        "img": "./images/37. 결혼까지 생각했어.jpg",
		"elbumTitle": "RealSlow is Back",
        "elbumImage": "",
		"debut" :"2002년 4월 3일", 
		"genre": "pop",
		"agency": "REALSLOW",
		"activity": "솔로"
	},
    {
        "id": 38,
        "title": "외톨이야",
        "singer": "씨엔블루",
        "img": "./images/38. 외톨이야.jpg",
		"elbumTitle": "Bluetory",
        "elbumImage": "",
		"debut" :"2010년 1월 14일", 
		"genre": "팝 록, 모던 록",
		"agency": "카카오엔터테인먼트 ",
		"activity": "그룹"
	},
    {
        "id": 39,
        "title": "Bubble Pop!",
        "singer": "현아",
        "img": "./images/39. Bubble Pop!.jpg",
		"elbumTitle": "Bubble Pop!",
        "elbumImage": "",
		"debut" :"2007년", 
		"genre": "팝",
		"agency": "무소속",
		"activity": "솔로"
	},
    {
        "id": 40,
        "title": "so Hot",
        "singer": "원더걸스",
        "img": "./images/40. so Hot.jpg",
		"elbumTitle": "so Hot",
        "elbumImage": "",
		"debut" :"2007년 2월 10일", 
		"genre": "댄스, 발라드, R&B, 밴드, 랩/힙합, 레게, 록, EDM, POP, 일렉트로닉, 하우스, 소울 등",
		"agency": "JYP",
		"activity": "그룹"
	},
    {
        "id": 41,
        "title": "abracadabra",
        "singer": "브라운아이드걸스",
        "img": "./images/41. abracadabra.jpg",
		"elbumTitle": "Sound G.",
        "elbumImage": "",
		"debut" :"2006년 3월 2일", 
		"genre": "R&B, 발라드, K-POP 등",
		"agency": "미스틱스토리",
		"activity": "그룹"
	},
    {
        "id": 42,
        "title": "시간을 달려서",
        "singer": "여자친구",
        "img": "./images/42. 시간을 달려서.jpg",
		"elbumTitle": "SNOWFLAKE",
        "elbumImage": "",
		"debut" :"2015년 1월 16일", 
		"genre": "댄스, 발라드",
		"agency": "쏘스뮤직",
		"activity": "그룹"
	},
    {
        "id": 43,
        "title": "아무노래",
        "singer": "지코",
        "img": "./images/43. 아무노래.jpg",
		"elbumTitle": "",
        "elbumImage": "",
		"debut" :"2011년 4월 15일", 
		"genre": "힙합/랩",
		"agency": "KOZ 엔터테인먼트",
		"activity": "솔로"
	},
    {
        "id": 44,
        "title": "Dolphin",
        "singer": "오마이걸",
        "img": "./images/44. Dolphin.jpg",
		"elbumTitle": "살짝 설렜어(Nonstop)",
        "elbumImage": "",
		"debut" :"2015년 4월 21일", 
		"genre": "댄스, 발라드, 락, 애니메이션",
		"agency": "WM",
		"activity": "그룹"
	},
    {
        "id": 45,
        "title": "눈누난나",
        "singer": "제시",
        "img": "./images/45. 눈누난나.jpg",
		"elbumTitle": "NUNA",
        "elbumImage": "",
		"debut" :"2005년 12월 1일", 
		"genre": "pop",
		"agency": "MORE VISION",
		"activity": "솔로"
	},
    {
        "id": 46,
        "title": "W/X/Y",
        "singer": "타니 유우키",
        "img": "./images/46. W/X/Y.jpg",
		"elbumTitle": "Memories",
        "elbumImage": "",
		"debut" :"2021년 12월 8일", 
		"genre": "J팝",
		"agency": "valley records",
		"activity": "솔로"
	},
    {
        "id": 47,
        "title": "책을 넘기는 듯한 마음으로",
        "singer": "homezone",
        "img": "./images/47. 책을 넘기는 듯한 마음으로.jpg",
		"elbumTitle": "",
        "elbumImage": "",
		"debut" :"2019년", 
		"genre": "R&B/Soul",
		"agency": "gardenonmars",
		"activity": "솔로"
	},
    {
        "id": 48,
        "title": "comedy",
        "singer": "시온",
        "img": "./images/48. comedy.jpg",
		"elbumTitle": "love",
        "elbumImage": "",
		"debut" :"2018년 4월 10일", 
		"genre": "가요, R&B, Soul",
		"agency": "뷰티플노이즈",
		"activity": "SyndromZ"
	},
    {
        "id": 49,
        "title": "유라",
        "singer": "수영해",
        "img": "./images/49. 수영해.jpg",
		"elbumTitle": "Virus Mix",
        "elbumImage": "",
		"debut" :"2018년", 
		"genre": "k팝",
		"agency": "문화인",
		"activity": "솔로"
	},

];