let albums= [
    {
        "id": 1,
        "title": "we are",
        "singer": "ONE OK ROCK",
        "img": "./images/10. we are.jpg",
        "elbumImage": "./images/img/ONE OK ROCK.jpg",
        "elbumImage1": "./images/img/ONE OK ROCK1.jpg",
        "elbumImage2": "./images/img/ONE OK ROCK2.jpg",
        "elbumImage3": "./images/img/ONE OK ROCK3.jpg",
        "profile": "./images/profile/ONE OK ROCK.jpg",

        "elbumTitle": "人生 x 僕 =",
        "elbumTitle1": "Wonder",
        "elbumTitle2": "Eye of the Storm",
        "elbumTitle3": "Make It Out Alive",
		"debut" :"2007년 11월 21일", 
		"genre": "록, 팝록, 파워 팝, 밴드",
		"agency": "10969",
		"activity": "밴드",
        "music":"./music/We Are.mp3"
	},
    {
        "id": 2,
        "title": "KIDDING",
        "singer": "이세계아이돌",
        "img": "./images/2. 키딩.jpg",
        "elbumImage": "./images/img/이세돌.jpg",
        "elbumImage1": "./images/img/이세돌1.jpg",
        "elbumImage2": "./images/img/이세돌2.jpg",
        "elbumImage3": "./images/img/이세돌3.jpg",
        "profile": "./images/profile/이세계아이돌.jpg",

        "elbumTitle": "KIDDING",
        "elbumTitle1": "RE : WIND",
        "elbumTitle2": "LOCKDOWN",
        "elbumTitle3": "겨울봄",
		"debut" :"2021년 12월 17일", 
		"genre": "댄스, 발라드, 팝, EDM",
		"agency": "패러블 엔터테인먼트",
		"activity": "그룹",
        "music":"./music/키딩.mp3"
	},
    {
        "id": 3,
        "title": "산책",
        "singer": "OVAN",
        "img": "./images/14. 산책.jpg",
        "elbumImage": "./images/img/오반.jpg",
        "elbumImage1": "./images/img/오반1.jpg",
        "elbumImage2": "./images/img/오반2.jpg",
        "elbumImage3": "./images/img/오반3.jpg",
        "profile": "./images/profile/OVAN.jpg",

        "elbumTitle": "Listen-UpEP.8",
        "elbumTitle1": "비가 오잖아",
        "elbumTitle2": "취한 밤",
        "elbumTitle3": "지금 난",
		"debut" :"2017년 3월 2일", 
		"genre": "싱어송라이트",
		"agency": "로맨틱팩토리",
		"activity": "솔로",
        "music":"./music/산책.mp3"        
	},
    {

        "id": 4,
        "title": "IDGAF",
        "singer": "Dua Lipa",
        "img": "./images/5. IDGAF.jpg",
        "elbumImage": "./images/img/Dua Lipa.jpg",
        "elbumImage1": "./images/img/Dua Lipa1.jpg",
        "elbumImage2": "./images/img/Dua Lipa2.jpg",
        "elbumImage3": "./images/img/Dua Lipa3.jpg",
        "profile": "./images/profile/Dua Lipa.jpg",

        "elbumTitle": "Sweetest Pie",
        "elbumTitle1": "Real Groove",
        "elbumTitle2": "100Greatest10s",
        "elbumTitle3": "Hallucinate",
		"debut" :"2015년", 
		"agency": "워너 뮤직 그룹",
		"activity": "솔로",
        "music":"./music/IDGAF.mp3"
	},
    {
        "id": 5,
        "title": "휠릴리",
        "singer": "이수영",
        "img": "./images/32. 휠릴리.jpg",
        "elbumImage": "./images/img/이수영.jpg",
        "elbumImage1": "./images/img/이수영1.jpg",
        "elbumImage2": "./images/img/이수영2.jpg",
        "elbumImage3": "./images/img/이수영3.jpg",
        "profile": "./images/profile/이수영.jpg",

        "elbumTitle": "This Time",
        "elbumTitle1": "I Believe",
        "elbumTitle2": "Autumn Of Memory",
        "elbumTitle3": "장옥정, 사랑에 살다",
		"debut" :"1999.11.17", 
		"genre": "발라드, 국내드라마, 댄스,",
		"agency": "뉴에라프로젝트",
		"activity": "솔로",
        "music":"./music/휠릴리.mp3"
	},
    {
        "id": 6,
        "title": "맞네",
        "singer": "루씨",
        "img": "./images/17. 맞네.jpg",
        "elbumImage": "./images/img/루씨.jpg",
        "elbumImage1": "./images/img/루씨1.jpg",
        "elbumImage2": "./images/img/루씨2.jpg",
        "elbumImage3": "./images/img/루씨3.jpg",
        "profile": "./images/profile/루씨.jpg",

        "elbumTitle": "PANORAMA",
        "elbumTitle1": "Childhood",
        "elbumTitle2": "Gatcha!",
        "elbumTitle3": "열",
		"debut" :"2020년 5월 8일", 
		"genre": "앱비언스 팝, 록, 일렉트로니카, R&B",
		"agency": "미스틱스토리",
		"activity": "그룹",
        "music":"./music/맞네.mp3"
	},
    {
        "id": 7,
        "title": "Braindead",
        "singer": "시온",
        "img": "./images/48. comedy.jpg",
        "elbumImage": "./images/img/시온.jpg",
        "elbumImage1": "./images/img/시온1.jpg",
        "elbumImage2": "./images/img/시온2.jpg",
        "elbumImage3": "./images/img/시온3.jpg",
        "profile": "./images/profile/시온.jpg",

        "elbumTitle": "첫 번째 '기억'",
        "elbumTitle1": "Flying Fish",
        "elbumTitle2": "Dirt Cheap",
        "elbumTitle3": "Love or Die",
		"debut" :"2018년 4월 10일", 
		"genre": "가요, R&B, Soul",
		"agency": "뷰티플노이즈",
		"activity": "SyndromZ",
        "music":"./music/Braindead.mp3"
	},
    {
        "id": 8,
        "title": "미인",
        "singer": "신중현과 엽전들",
        "img": "./images/23. 미인.jpg",
        "elbumImage": "./images/img/신중현과 엽전들.jpg",
        "elbumImage1": "./images/img/신중현과 엽전들1.jpg",
        "elbumImage2": "./images/img/신중현과 엽전들2.jpg",
        "elbumImage3": "./images/img/신중현과 엽전들3.jpg",
        "profile": "./images/profile/신중현과 엽전들.jpg",

        "elbumTitle": "락그룹 콘서트",
        "elbumTitle1": "낭만시대 G",
        "elbumTitle2": "한국의 록 그룹",
        "elbumTitle3": "SHIN JUNG HYUN",
		"debut" :"1974년 8월 25일", 
		"genre": "사이키델릭 록, 하드 록, R&B",
		"agency": "지구레코드",
		"activity": "그룹",
        "music":"./music/미인.mp3"
	},
    {
        "id": 9,
        "title": "Love",
        "singer": "homezone",
        "img": "./images/47. 책을 넘기는 듯한 마음으로.jpg",
        "elbumImage": "./images/img/homezone.jpg",
        "elbumImage1": "./images/img/homezone1.jpg",
        "elbumImage2": "./images/img/homezone2.jpg",
        "elbumImage3": "./images/img/homezone3.jpg",
        "profile": "./images/profile/homezone.jpg",

        "elbumTitle": "Winded",
        "elbumTitle1": "bright #11",
        "elbumTitle2": "Fault",
        "elbumTitle3": "moving on",
		"debut" :"2019년 8월", 
		"genre": "R&B/Soul, 인디음악",
		"agency": "가든온마스",
		"activity": "솔로",
        "music":"./music/Love.mp3"
	},
    {
        "id": 10,
        "title": "수영해",
        "singer": "유라",
        "img": "./images/49. 수영해.jpg",
        "elbumImage": "./images/img/유라.jpg",
        "elbumImage1": "./images/img/유라1.jpg",
        "elbumImage2": "./images/img/유라2.jpg",
        "elbumImage3": "./images/img/유라3.jpg",
        "profile": "./images/profile/수영해.jpg",

        "elbumTitle": "GAUSSIAN",
        "elbumTitle1": "B side",
        "elbumTitle2": "Jungle Bike",
        "elbumTitle3": "하양",
		"debut" :"2018.10.01", 
		"genre": "R&B/Soul, 인디음악, 일렉트로니카, 록/메탈, 국내드라마, 재즈, 애시드/퓨전/팝, 댄스",
		"agency": "개인",
		"activity": "솔로",
        "music":"./music/유라.mp3"
	},
    {
        "id": 11,
        "title": "어쩌나",
        "singer": "소금",
        "img": "./images/11. Imagin.jpg",
        "elbumImage": "./images/img/소금.jpg",
        "elbumImage1": "./images/img/소금1.jpg",
        "elbumImage2": "./images/img/소금2.jpg",
        "elbumImage3": "./images/img/소금3.jpg",
        "profile": "./images/profile/소금.jpg",

        "elbumTitle": "January Never Dies",
        "elbumTitle1": "Precious",
        "elbumTitle2": "Sobrightttttttt",
        "elbumTitle3": "Not my fault",
		"debut" :"2019년 10월 21일", 
		"genre": "R&B/Soul, 랩/힙합, 일렉트로니카, 국내드라마, 댄스, 인디음악, 록/메탈",
		"agency": "무속",
		"activity": "솔로",
        "music":"./music/어쩌나.mp3"
	},
    {
        "id": 12,
        "title": "악몽",
        "singer": "애쉬 아일랜드",
        "img": "./images/12. 악몽.jpg",
        "elbumImage": "./images/img/애쉬아일랜드.jpg",
        "elbumImage1": "./images/img/애쉬아일랜드1.jpg",
        "elbumImage2": "./images/img/애쉬아일랜드2.jpg",
        "elbumImage3": "./images/img/애쉬아일랜드3.jpg",
        "profile": "./images/profile/애쉬 아일랜드.jpg",

        "elbumTitle": "Paranoid Remix",
        "elbumTitle1": "멜로디",
        "elbumTitle2": "More ISLAND",
        "elbumTitle3": "ISLAND",
        "debut" :"2018년 11월 12일", 
        "genre": "힙합, R&B, 이모 랩, 트랩, 록, 팝",
        "agency": "AMBITION MUSIK ",
        "activity": "PABLO MU2IK",
        "music":"./music/악몽.mp3"
	},
];